PWD /home/archie/shares/School/Personal_School
INPUT /etc/texmf/web2c/texmf.cnf
INPUT /usr/share/texmf/web2c/texmf.cnf
INPUT /usr/share/texlive/texmf-dist/web2c/texmf.cnf
INPUT /var/lib/texmf/web2c/pdftex/latex.fmt
INPUT Makefile
OUTPUT Makefile.log
